/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void arrayListReturnsJsonObjectSizeTest() {
    }
    @Test void quoteTest(){
    }
}
