/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Random;

//import org.json.*;

public class App {


    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();
        File quoteFile = new File("./app/src/test/resources/recentquotes.json");
        FileReader reader = new FileReader(quoteFile);
        Type collectionType = new TypeToken<Collection<Quote>>(){}.getType();
        ArrayList<Quote> list = gson.fromJson(reader, collectionType);
        Random random = new Random();
        int n = random.nextInt(138);
        System.out.println(list.get(n).author);
        System.out.println(list.get(n).text);

    }


}
